-- ==============================================================================
-- نظام إدارة الحلقات والمتابعة الشاملة
-- سكريبت إنشاء قاعدة البيانات (هيكل نظيف خالي من البيانات التجريبية)
-- ==============================================================================

-- 1. تفعيل إضافات التشفير وتوليد UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- 2. جدول معلومات وإعدادات المركز (center_info)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.center_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL DEFAULT 'مركز تحفيظ القرآن الكريم',
    address TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL DEFAULT '',
    logo TEXT DEFAULT '',
    hijri_year TEXT NOT NULL DEFAULT '1446 هـ',
    academic_season TEXT NOT NULL DEFAULT 'الفصل الدراسي الأول',
    manager_name TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- إدراج صف افتراضي لإعدادات المركز لتجنب أخطاء الواجهة عند الجلب
INSERT INTO public.center_info (id, name, address, phone, email, hijri_year, academic_season, manager_name)
VALUES (1, 'مركز تحفيظ القرآن الكريم', 'العنوان', '00000000', 'info@example.com', '1446 هـ', 'الفصل الدراسي الأول', 'مدير المركز')
ON CONFLICT (id) DO NOTHING;

-- ==============================================================================
-- 3. جدول الحسابات والمستخدمين والصلاحيات (profiles) المرتبط بـ auth.users
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    phone TEXT,
    role TEXT NOT NULL CHECK (role IN ('admin', 'sheikh', 'parent', 'data_entry')),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended')),
    permissions JSONB NOT NULL DEFAULT '{"manage_students": false}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- 4. مشغل (Trigger) للربط التلقائي الفوري بين auth.users و public.profiles
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    v_username TEXT;
    v_name TEXT;
    v_phone TEXT;
    v_role TEXT;
BEGIN
    v_username := COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1));
    v_name := COALESCE(NEW.raw_user_meta_data->>'name', 'مستخدم جديد');
    v_phone := COALESCE(NEW.raw_user_meta_data->>'phone', '');
    v_role := COALESCE(NEW.raw_user_meta_data->>'role', 'parent');

    IF EXISTS (SELECT 1 FROM public.profiles WHERE username = v_username AND id <> NEW.id) THEN
        v_username := v_username || '_' || substr(replace(NEW.id::text, '-', ''), 1, 4);
    END IF;

    INSERT INTO public.profiles (id, user_id, username, email, name, phone, role, status, permissions)
    VALUES (
        NEW.id, NEW.id, v_username, NEW.email, v_name, v_phone, v_role, 'active',
        CASE 
            WHEN v_role = 'admin' THEN '{"manage_students": true, "manage_sheikhs": true, "manage_admins": true, "daily_recitation": true, "manage_exams": true, "print_reports": true, "honor_board": true, "center_settings": true, "manage_accounts": true, "archive_season": true}'::jsonb
            WHEN v_role = 'sheikh' THEN '{"manage_students": false, "manage_sheikhs": false, "manage_admins": false, "daily_recitation": true, "manage_exams": true, "print_reports": true, "honor_board": true, "center_settings": false, "manage_accounts": false, "archive_season": false}'::jsonb
            WHEN v_role = 'data_entry' THEN '{"manage_students": true, "manage_sheikhs": false, "manage_admins": false, "daily_recitation": true, "manage_exams": true, "print_reports": true, "honor_board": true, "center_settings": false, "manage_accounts": false, "archive_season": false}'::jsonb
            ELSE '{"manage_students": false, "manage_sheikhs": false, "manage_admins": false, "daily_recitation": false, "manage_exams": false, "print_reports": false, "honor_board": false, "center_settings": false, "manage_accounts": false, "archive_season": false}'::jsonb
        END
    )
    ON CONFLICT (id) DO UPDATE SET
        user_id = EXCLUDED.user_id, username = EXCLUDED.username, email = EXCLUDED.email, name = EXCLUDED.name, phone = EXCLUDED.phone, role = EXCLUDED.role;

    RETURN NEW;
EXCEPTION WHEN OTHERS THEN
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==============================================================================
-- 4.1. دالة RPC موحدة لإنشاء وتأكيد أي مستخدم في auth.users و profiles مباشرة
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.admin_create_auth_user(
    p_email TEXT, p_password TEXT, p_username TEXT, p_name TEXT, p_phone TEXT, p_role TEXT
)
RETURNS UUID AS $$
DECLARE
    new_user_id UUID;
BEGIN
    SELECT id INTO new_user_id FROM auth.users WHERE email = p_email LIMIT 1;
    
    IF new_user_id IS NOT NULL THEN
        UPDATE auth.users 
        SET encrypted_password = crypt(p_password, gen_salt('bf')),
            raw_user_meta_data = jsonb_build_object('username', p_username, 'name', p_name, 'phone', p_phone, 'role', p_role),
            email_confirmed_at = COALESCE(email_confirmed_at, NOW()), updated_at = NOW()
        WHERE id = new_user_id;
    ELSE
        new_user_id := gen_random_uuid();
        INSERT INTO auth.users (id, instance_id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, role, aud) 
        VALUES (new_user_id, '00000000-0000-0000-0000-000000000000', p_email, crypt(p_password, gen_salt('bf')), NOW(), '{"provider":"email","providers":["email"]}'::jsonb, jsonb_build_object('username', p_username, 'name', p_name, 'phone', p_phone, 'role', p_role), NOW(), NOW(), 'authenticated', 'authenticated');
    END IF;

    INSERT INTO public.profiles (id, user_id, username, email, name, phone, role, status, permissions)
    VALUES (new_user_id, new_user_id, p_username, p_email, p_name, p_phone, p_role, 'active',
        CASE 
            WHEN p_role = 'admin' THEN '{"manage_students": true, "manage_sheikhs": true, "manage_admins": true, "daily_recitation": true, "manage_exams": true, "print_reports": true, "honor_board": true, "center_settings": true, "manage_accounts": true, "archive_season": true}'::jsonb
            WHEN p_role = 'sheikh' THEN '{"manage_students": false, "manage_sheikhs": false, "manage_admins": false, "daily_recitation": true, "manage_exams": true, "print_reports": true, "honor_board": true, "center_settings": false, "manage_accounts": false, "archive_season": false}'::jsonb
            WHEN p_role = 'data_entry' THEN '{"manage_students": true, "manage_sheikhs": false, "manage_admins": false, "daily_recitation": true, "manage_exams": true, "print_reports": true, "honor_board": true, "center_settings": false, "manage_accounts": false, "archive_season": false}'::jsonb
            ELSE '{"manage_students": false, "manage_sheikhs": false, "manage_admins": false, "daily_recitation": false, "manage_exams": false, "print_reports": false, "honor_board": false, "center_settings": false, "manage_accounts": false, "archive_season": false}'::jsonb
        END
    )
    ON CONFLICT (id) DO UPDATE SET user_id = EXCLUDED.user_id, username = EXCLUDED.username, email = EXCLUDED.email, name = EXCLUDED.name, phone = EXCLUDED.phone, role = EXCLUDED.role;

    RETURN new_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.admin_create_auth_user(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO anon, authenticated, service_role;

-- ==============================================================================
-- 5. جدول المشايخ والمحفظين (sheikhs)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.sheikhs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    civil_id TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    username TEXT,
    halqa_name TEXT NOT NULL,
    bio TEXT,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- 6. جدول الكادر الإداري والمشرفين (admins)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    civil_id TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    username TEXT,
    job_title TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'admin',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- 7. جدول الطلاب (students)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    civil_id TEXT NOT NULL,
    dob DATE,
    age INT NOT NULL DEFAULT 10,
    grade TEXT NOT NULL DEFAULT 'المتوسط',
    parent_name TEXT,
    parent_phone TEXT NOT NULL,
    parent_email TEXT NOT NULL DEFAULT '',
    parent_username TEXT,
    sheikh_id BIGINT REFERENCES public.sheikhs(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    join_date DATE NOT NULL DEFAULT CURRENT_DATE,
    current_juz INT NOT NULL DEFAULT 1,
    target_juz INT NOT NULL DEFAULT 5,
    points INT NOT NULL DEFAULT 100,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- 8. جدول سجلات التسميع اليومي والمتابعة (tracking)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.tracking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    sheikh_id BIGINT REFERENCES public.sheikhs(id) ON DELETE SET NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    new_surah TEXT,
    new_from INT,
    new_to INT,
    rev_surah TEXT,
    rev_from INT,
    rev_to INT,
    big_rev_surah TEXT,
    big_rev_from INT,
    big_rev_to INT,
    att TEXT NOT NULL DEFAULT 'حضوري',
    eval TEXT NOT NULL DEFAULT 'ممتاز',
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'approved' CHECK (status IN ('draft', 'approved')),
    read_by_parent BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- 9. جدول ملاحظات المشايخ لأولياء الأمور (notes)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    sheikh_id BIGINT REFERENCES public.sheikhs(id) ON DELETE SET NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    text TEXT NOT NULL,
    priority TEXT NOT NULL DEFAULT 'عادي' CHECK (priority IN ('عادي', 'هام', 'تنبيه غياب', 'تشجيع')),
    read_by_parent BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- 10. جدول الاختبارات القرآنية (exams)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    type TEXT NOT NULL,
    part_or_surah TEXT NOT NULL,
    grade TEXT NOT NULL DEFAULT 'ممتاز مرتفع',
    score NUMERIC(5,2) NOT NULL DEFAULT 95.0,
    examiner TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- 11. جدول الأوسمة ولوحة الشرف (badges)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.badges (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    icon TEXT NOT NULL DEFAULT '👑',
    description TEXT,
    date_earned DATE NOT NULL DEFAULT CURRENT_DATE
);

-- ==============================================================================
-- 12. تفعيل سياسات الأمان Row Level Security (RLS)
-- ==============================================================================
ALTER TABLE public.center_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sheikhs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.badges ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    DROP POLICY IF EXISTS "Allow full access on center_info" ON public.center_info;
    CREATE POLICY "Allow full access on center_info" ON public.center_info FOR ALL USING (true);

    DROP POLICY IF EXISTS "Allow full access on profiles" ON public.profiles;
    CREATE POLICY "Allow full access on profiles" ON public.profiles FOR ALL USING (true);

    DROP POLICY IF EXISTS "Allow full access on sheikhs" ON public.sheikhs;
    CREATE POLICY "Allow full access on sheikhs" ON public.sheikhs FOR ALL USING (true);

    DROP POLICY IF EXISTS "Allow full access on admins" ON public.admins;
    CREATE POLICY "Allow full access on admins" ON public.admins FOR ALL USING (true);

    DROP POLICY IF EXISTS "Allow full access on students" ON public.students;
    CREATE POLICY "Allow full access on students" ON public.students FOR ALL USING (true);

    DROP POLICY IF EXISTS "Allow full access on tracking" ON public.tracking;
    CREATE POLICY "Allow full access on tracking" ON public.tracking FOR ALL USING (true);

    DROP POLICY IF EXISTS "Allow full access on notes" ON public.notes;
    CREATE POLICY "Allow full access on notes" ON public.notes FOR ALL USING (true);

    DROP POLICY IF EXISTS "Allow full access on exams" ON public.exams;
    CREATE POLICY "Allow full access on exams" ON public.exams FOR ALL USING (true);

    DROP POLICY IF EXISTS "Allow full access on badges" ON public.badges;
    CREATE POLICY "Allow full access on badges" ON public.badges FOR ALL USING (true);
END $$;
